#!/usr/bin/env python3
"""
Aggregate all rebuttal experiment outputs into a single markdown summary
that can be quoted verbatim in the WoGp rebuttal.

Reads:
  - results/rebuttal/exp1/per_seed.csv   (Protocol A vs B)
  - results/rebuttal/exp2/per_seed.csv   (Polaris multi vs single annotator)
  - results/rebuttal/exp3/per_seed.csv   (per-judge per-dataset RSG with seeds)
  - results/rebuttal/exp3/rsg_with_95ci.csv (post-bootstrap CIs; generated by exp3)
  - results/v2/r2ccp_per_dataset.csv     (paper baseline numbers, for cross-check)

Writes:
  - results/rebuttal/REBUTTAL_TABLES.md
"""
import os
import numpy as np
import pandas as pd
from scipy.stats import ttest_rel

ROOT = '/ssd_4TB/divake/VLM_Judge_Uncertainty'
os.chdir(ROOT)

out = ['# WoGp Rebuttal — All Experimental Results', '']

# ---------- Exp 1 ----------
out.append('## Exp 1: External 40/10/50 split for R2CCP (addresses R1)\n')
p = 'results/rebuttal/exp1/per_seed.csv'
if os.path.exists(p):
    df1 = pd.read_csv(p)
    out.append(f"- Per-seed records: {len(df1)} across {df1.judge.nunique()} judges, "
               f"{df1.protocol.nunique()} protocols, {df1.seed.nunique()} seeds.\n")
    out.append('| Judge | Protocol | Cov(raw) | Width(raw) | Cov(adj) | Width(adj) |')
    out.append('|---|---|---|---|---|---|')
    g = df1.groupby(['judge','protocol']).agg(
        cov_raw_m=('cov_raw','mean'),  cov_raw_s=('cov_raw','std'),
        w_raw_m=('width_raw','mean'),  w_raw_s=('width_raw','std'),
        cov_adj_m=('cov_adj','mean'),  cov_adj_s=('cov_adj','std'),
        w_adj_m=('width_adj','mean'),  w_adj_s=('width_adj','std'),
    ).reset_index()
    for _, r in g.iterrows():
        out.append(f"| {r['judge']} | {r['protocol']} | "
                   f"{r['cov_raw_m']:.4f}±{r['cov_raw_s']:.4f} | {r['w_raw_m']:.4f}±{r['w_raw_s']:.4f} | "
                   f"{r['cov_adj_m']:.4f}±{r['cov_adj_s']:.4f} | {r['w_adj_m']:.4f}±{r['w_adj_s']:.4f} |")
    # Paired t-test of A vs B per judge
    out.append('\n### Paired t-test (per-seed Protocol A vs Protocol B)\n')
    out.append('| Judge | Δ cov_raw (A−B) | p-value (cov_raw) | Δ width_raw (A−B) | p-value (width_raw) |')
    out.append('|---|---|---|---|---|')
    for j in df1.judge.unique():
        sub = df1[df1.judge == j]
        a = sub[sub.protocol == 'A_internal_split'].sort_values('seed')
        b = sub[sub.protocol == 'B_external_split'].sort_values('seed')
        if len(a) == len(b) and len(a) > 1:
            d_cov = (a.cov_raw.values - b.cov_raw.values).mean()
            _, p_cov = ttest_rel(a.cov_raw.values, b.cov_raw.values)
            d_w = (a.width_raw.values - b.width_raw.values).mean()
            _, p_w = ttest_rel(a.width_raw.values, b.width_raw.values)
            out.append(f"| {j} | {d_cov:+.4f} | {p_cov:.3f} | {d_w:+.4f} | {p_w:.3f} |")
    out.append('\n*Interpretation:* if p > 0.05 for both, the two protocols are statistically '
               'indistinguishable, confirming that the conformal quantile is unchanged whether '
               'R2CCP splits internally or whether we hold out an external 10% calibration set.\n')
else:
    out.append('*(Exp 1 still running.)*\n')

# ---------- Exp 2 ----------
out.append('\n## Exp 2: Polaris single-annotator ablation (addresses R4)\n')
p = 'results/rebuttal/exp2/per_seed.csv'
if os.path.exists(p):
    df2 = pd.read_csv(p)
    out.append(f"- Per-seed records: {len(df2)} across {df2.arm.nunique()} arms × {df2.seed.nunique()} seeds.\n")
    out.append('| Arm | Cov(raw) | Width(raw) | Cov(adj) | Width(adj) |')
    out.append('|---|---|---|---|---|')
    g = df2.groupby('arm').agg(
        cov_raw_m=('cov_raw','mean'),  cov_raw_s=('cov_raw','std'),
        w_raw_m=('width_raw','mean'),  w_raw_s=('width_raw','std'),
        cov_adj_m=('cov_adj','mean'),  cov_adj_s=('cov_adj','std'),
        w_adj_m=('width_adj','mean'),  w_adj_s=('width_adj','std'),
    ).reset_index()
    for _, r in g.iterrows():
        out.append(f"| {r['arm']} | "
                   f"{r['cov_raw_m']:.4f}±{r['cov_raw_s']:.4f} | {r['w_raw_m']:.4f}±{r['w_raw_s']:.4f} | "
                   f"{r['cov_adj_m']:.4f}±{r['cov_adj_s']:.4f} | {r['w_adj_m']:.4f}±{r['w_adj_s']:.4f} |")
    if {'multi_annotator','single_annotator'}.issubset(df2.arm.unique()):
        a = df2[df2.arm=='multi_annotator'].sort_values('seed')
        b = df2[df2.arm=='single_annotator'].sort_values('seed')
        if len(a) == len(b) and len(a) > 1:
            d_w = (b.width_raw.values - a.width_raw.values).mean()
            _, p_w = ttest_rel(b.width_raw.values, a.width_raw.values)
            mult = b.width_raw.values.mean() / a.width_raw.values.mean()
            out.append(f"\n*Paired comparison:* single-annotator width is {mult:.2f}× the "
                       f"multi-annotator width on the same Polaris items, Δ = +{d_w:.3f}, p = {p_w:.4f}.")
            out.append(f"\n*Reference numbers from paper:*")
            out.append(f"- MLLM-Judge R2CCP raw width: 3.05 (single annotator, integer GT, 14-way VQA)")
            out.append(f"- Polaris   R2CCP raw width: 0.68 (multi annotator mean, continuous GT mapped to 1-5)")
            out.append(f"- Polaris   single-annotator: {b.width_raw.values.mean():.3f} (this experiment)")
            denom = max(3.05 - 0.68, 1e-9)
            isol = (b.width_raw.values.mean() - 0.68) / denom * 100
            out.append(f"\n*Implication:* aggregation alone accounts for {isol:.0f}% of the 3.05 - 0.68 = 2.37 width gap "
                       "(everything else — task type, label continuity, etc. — accounts for the remainder).")
else:
    out.append('*(Exp 2 still running.)*\n')

# ---------- Exp 3 ----------
out.append('\n## Exp 3: Bootstrap 95% CIs on ρ, width, RSG (addresses R5c)\n')
p_ci = 'results/rebuttal/exp3/rsg_with_95ci.csv'
if os.path.exists(p_ci):
    ci = pd.read_csv(p_ci)
    out.append(f"- Rows: {len(ci)} (dataset × judge); N=10 seeds per row; bootstrap B=2000.\n")
    out.append('### Table: RSG with 95% bootstrap CIs (replaces paper Table 17)\n')
    out.append('| Judge | Dataset | ρ (95% CI) | Width (95% CI) | RSG (95% CI) |')
    out.append('|---|---|---|---|---|')
    for _, r in ci.iterrows():
        rho_s = f"{r['pearson_mean']:+.3f} [{r['pearson_lo']:+.3f}, {r['pearson_hi']:+.3f}]"
        w_s   = f"{r['width_mean']:.3f} [{r['width_lo']:.3f}, {r['width_hi']:.3f}]"
        rsg_s = f"{r['rsg_mean']:+.3f} [{r['rsg_lo']:+.3f}, {r['rsg_hi']:+.3f}]"
        out.append(f"| {r['judge']} | {r['dataset']} | {rho_s} | {w_s} | {rsg_s} |")
else:
    out.append('*(Exp 3 still running.)*\n')

# ---------- Corrected width percentages (no new experiment needed) ----------
out.append('\n## Width-as-percent-of-score-range, corrected to ÷(K-1)=÷4\n')
p_orig = 'results/v2/r2ccp_per_dataset.csv'
if os.path.exists(p_orig):
    df = pd.read_csv(p_orig)
    out.append('Paper §4 defines width range on a 1-5 scale as 0 to 4. Therefore the correct '
               'normalization is ÷(K-1)=÷4. Paper §5.4 already uses ÷4 correctly; Table 7 '
               'incorrectly used ÷5. Corrected numbers:\n')
    out.append('| Dataset | Width | Paper (÷5, wrong) | Corrected (÷4) |')
    out.append('|---|---|---|---|')
    for _, r in df.sort_values('width_raw').iterrows():
        w = r['width_raw']
        out.append(f"| {r['dataset']} | {w:.3f} | {100*w/5:.1f}% | {100*w/4:.1f}% |")
    out.append(f"\n**MLLM-Judge average:** width 2.84 → {100*df.width_raw.mean()/4:.1f}% (correct ÷4), "
               f"NOT 61% as Table 7 states (61% came from incorrectly using 3.05/5).")
    out.append(f"\n**Polaris:** width 0.68 → 17.0% (correct ÷4), NOT 14% (14% came from 0.68/5).")
    out.append(f"\n**Abstract correction:** the narrowest task (AesBench) covers 52% of the range, "
               f"not ~40%. The widest task (InfographicsVQA) covers 88%, not ~70%. We will update "
               f"the abstract to: 'intervals span 52–88% of the score range across 14 task categories, "
               f"with aesthetics/natural-image tasks at the low end and chart/math reasoning at the high end.'")

# ---------- Write ----------
out_path = 'results/rebuttal/REBUTTAL_TABLES.md'
with open(out_path, 'w') as f:
    f.write('\n'.join(out))
print(f"Wrote: {out_path}")
print('\n'.join(out[-30:]))
