#!/usr/bin/env python3
"""Lean judge inference for Polaris captioning evaluation dataset.

Task: Given an image and a generated caption, rate the caption quality 1-5.

Outputs same CSV format:
    sample_id, s2_lp1, s2_lp2, s2_lp3, s2_lp4, s2_lp5, gt_score, parsed_score

Usage:
    CUDA_VISIBLE_DEVICES=0 conda run -n env_py311 python scripts/run_judge_polaris.py --start-idx 0 --end-idx 4363 --output results/v2_polaris/features_s2_p0.csv &
    CUDA_VISIBLE_DEVICES=1 conda run -n env_py311 python scripts/run_judge_polaris.py --start-idx 4363 --end-idx 8726 --output results/v2_polaris/features_s2_p1.csv &
"""

import argparse
import copy
import csv
import gc
import math
import os
import sys
import time

import torch
import torch.nn.functional as F
import pandas as pd
from PIL import Image
from tqdm import tqdm

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

SCORE_TOKENS = ["1", "2", "3", "4", "5"]
FALLBACK_LP = math.log(1e-5)

# Captioning evaluation prompt — same rubric structure, adapted for caption quality
PROMPT_TEMPLATE = """Please serve as an unbiased judge in assessing the quality of an image caption generated by an AI model.

Evaluation Steps:
Please examine the provided image attentively. Then evaluate how well the generated caption describes the image content.

Scoring Rubric:
Poor (1): The caption is completely inaccurate, irrelevant, or fails to describe the image content. Major factual errors or hallucinations are present.
Fair (2): The caption partially describes the image but has significant inaccuracies, missing key elements, or includes incorrect details.
Average (3): The caption adequately describes the main content of the image with fair accuracy, but may miss some details or include minor inaccuracies.
Good (4): The caption accurately describes the image content with good detail and relevance, with only minor omissions.
Excellent (5): The caption perfectly describes the image content with high accuracy, comprehensive detail, and excellent relevance to what is shown.

Notice:
Evaluate based on accuracy, relevance to the image, comprehensiveness, and level of detail. Do not allow caption length to influence your evaluation. Be as objective as possible.

Here is the input:
[The Image]
(See the attached image)
[The Generated Caption]
{caption}

Provide your analysis of how well the caption matches the image, then provide your final score in exactly this format on its own line: "Score: X" where X is a single number from 1 to 5."""


def load_model(device="cuda:0"):
    """Load LLaVA-Critic model."""
    from transformers import AutoTokenizer, AutoConfig, Qwen2Config
    from llava.model.language_model.llava_qwen import LlavaQwenForCausalLM

    model_path = "models/llava-critic-7b"
    config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
    if hasattr(config, 'text_config') and isinstance(config.text_config, dict):
        config.text_config = Qwen2Config(**config.text_config)

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = LlavaQwenForCausalLM.from_pretrained(
        model_path, low_cpu_mem_usage=True, attn_implementation="sdpa",
        torch_dtype=torch.float16, device_map="auto", config=config,
    )
    model.eval()
    vision_tower = model.get_vision_tower()
    if not vision_tower.is_loaded:
        vision_tower.load_model()
    image_processor = vision_tower.image_processor
    return model, tokenizer, image_processor


def run_inference(model, tokenizer, image_processor, image_path, prompt, max_new_tokens=1024):
    """Run LLaVA-Critic inference."""
    from llava.mm_utils import process_images, tokenizer_image_token
    from llava.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN
    from llava.conversation import conv_templates

    image = Image.open(image_path).convert("RGB")
    image_tensor = process_images([image], image_processor, model.config)
    image_tensor = [_img.to(dtype=torch.float16, device=model.device) for _img in image_tensor]

    conv_template = "qwen_1_5"
    question = DEFAULT_IMAGE_TOKEN + "\n" + prompt
    conv = copy.deepcopy(conv_templates[conv_template])
    conv.append_message(conv.roles[0], question)
    conv.append_message(conv.roles[1], None)
    prompt_text = conv.get_prompt()

    input_ids = tokenizer_image_token(
        prompt_text, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt"
    ).unsqueeze(0).to(model.device)

    with torch.no_grad():
        generation = model.generate(
            input_ids, images=image_tensor, image_sizes=[image.size],
            max_new_tokens=max_new_tokens, return_dict_in_generate=True,
            output_scores=True, do_sample=False, repetition_penalty=1.1,
        )

    sequences = generation.sequences
    scores = generation.scores
    input_length = sequences.shape[1] - len(scores)
    return scores, sequences, input_length


def extract_s2(scores, sequences, input_length, tokenizer):
    """Extract S2 logprobs and parsed score."""
    n_steps = len(scores)
    tokens = [tokenizer.decode([sequences[0, input_length + i].item()]).strip() for i in range(n_steps)]
    stripped = [t.lower() for t in tokens]

    score_idx = None
    for i in range(len(tokens) - 1, -1, -1):
        if stripped[i] in SCORE_TOKENS:
            for j in range(max(0, i - 3), i):
                if "score" in stripped[j]:
                    score_idx = i; break
            if score_idx: break
    if score_idx is None:
        for i in range(len(tokens) - 1, -1, -1):
            if stripped[i] in SCORE_TOKENS:
                score_idx = i; break

    if score_idx is None:
        return [FALLBACK_LP] * 5, -1

    step_scores = scores[score_idx]
    log_probs = F.log_softmax(step_scores.float(), dim=-1)

    s2 = []
    for s in SCORE_TOKENS:
        token_ids = tokenizer.encode(s, add_special_tokens=False)
        if len(token_ids) == 1:
            lp = log_probs[0, token_ids[0]].item()
            if not (lp == lp): lp = FALLBACK_LP
            s2.append(lp)
        else:
            s2.append(FALLBACK_LP)

    parsed_score = int(tokens[score_idx]) if tokens[score_idx] in SCORE_TOKENS else -1
    return s2, parsed_score


def main():
    parser = argparse.ArgumentParser(description="Polaris captioning judge → CSV")
    parser.add_argument("--output", type=str, required=True)
    parser.add_argument("--start-idx", type=int, default=0)
    parser.add_argument("--end-idx", type=int, default=None)
    parser.add_argument("--max-new-tokens", type=int, default=1024)
    args = parser.parse_args()

    # Load processed dataset
    df = pd.read_csv('data/polaris/polaris_test_processed.csv')
    print(f"[main] Dataset: {len(df)} samples")

    end_idx = args.end_idx or len(df)
    subset = df.iloc[args.start_idx:end_idx].reset_index(drop=True)
    print(f"[main] Processing {len(subset)} samples (idx {args.start_idx} to {end_idx})")

    # Load model
    model, tokenizer, image_processor = load_model()
    print("[main] Model loaded")

    # Prepare output
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    csv_file = open(args.output, "w", newline="")
    writer = csv.writer(csv_file)
    writer.writerow(["sample_id", "s2_lp1", "s2_lp2", "s2_lp3", "s2_lp4", "s2_lp5",
                      "gt_score", "parsed_score", "gt_score_continuous"])

    errors = 0
    pbar = tqdm(range(len(subset)), desc="Polaris judge inference")

    for i in pbar:
        row = subset.iloc[i]
        try:
            image_path = f"data/polaris/images/{row['imgid']}"
            if not os.path.exists(image_path):
                raise FileNotFoundError(f"Image not found: {image_path}")

            prompt = PROMPT_TEMPLATE.format(caption=row['mt'])

            scores_out, sequences, input_length = run_inference(
                model, tokenizer, image_processor, image_path, prompt,
                max_new_tokens=args.max_new_tokens,
            )

            s2, parsed_score = extract_s2(scores_out, sequences, input_length, tokenizer)

            # Map continuous 0-1 GT to 1-5 scale (discrete)
            gt_discrete = int(round(row['score_mean'] * 4) + 1)
            gt_discrete = max(1, min(5, gt_discrete))

            writer.writerow([args.start_idx + i, s2[0], s2[1], s2[2], s2[3], s2[4],
                             gt_discrete, parsed_score, row['score_mean']])
            csv_file.flush()

            del scores_out, sequences
            torch.cuda.empty_cache()

        except Exception as e:
            print(f"\n[ERROR] Sample {args.start_idx + i}: {e}")
            errors += 1
            gt_discrete = int(round(row['score_mean'] * 4) + 1)
            writer.writerow([args.start_idx + i, FALLBACK_LP, FALLBACK_LP, FALLBACK_LP,
                             FALLBACK_LP, FALLBACK_LP, gt_discrete, -1, row['score_mean']])
            csv_file.flush()

        pbar.set_postfix(err=errors)

    csv_file.close()
    print(f"\n[main] Done! {len(subset) - errors} succeeded, {errors} errors")
    print(f"[main] Output: {args.output}")

    del model, tokenizer, image_processor
    gc.collect()
    torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
