#!/usr/bin/env python3
"""Lean judge inference for Phi-4-reasoning-vision-15B.

Outputs same CSV format as run_judge_lean.py:
    sample_id, s2_lp1, s2_lp2, s2_lp3, s2_lp4, s2_lp5, gt_score, parsed_score

Usage:
    # Single GPU:
    CUDA_VISIBLE_DEVICES=0 conda run -n phi4_env python scripts/run_judge_phi4.py --output results/v2_phi4/features_s2.csv

    # Two GPUs:
    CUDA_VISIBLE_DEVICES=0 conda run -n phi4_env python scripts/run_judge_phi4.py --start-idx 0 --end-idx 2859 --output results/v2_phi4/features_s2_p0.csv &
    CUDA_VISIBLE_DEVICES=1 conda run -n phi4_env python scripts/run_judge_phi4.py --start-idx 2859 --end-idx 5717 --output results/v2_phi4/features_s2_p1.csv &
"""

import argparse
import csv
import gc
import json
import math
import os
import sys
import time

import torch
import torch.nn.functional as F
from PIL import Image
from tqdm import tqdm

SCORE_TOKENS = ["1", "2", "3", "4", "5"]
FALLBACK_LP = math.log(1e-5)

# Captioning evaluation prompt — same as Polaris LLaVA runner
PROMPT_TEMPLATE = """Please serve as an unbiased judge in assessing the quality of an image caption generated by an AI model.

Evaluation Steps:
Please examine the provided image attentively. Then evaluate how well the generated caption describes the image content.

Scoring Rubric:
Poor (1): The caption is completely inaccurate, irrelevant, or fails to describe the image content. Major factual errors or hallucinations are present.
Fair (2): The caption partially describes the image but has significant inaccuracies, missing key elements, or includes incorrect details.
Average (3): The caption adequately describes the main content of the image with fair accuracy, but may miss some details or include minor inaccuracies.
Good (4): The caption accurately describes the image content with good detail and relevance, with only minor omissions.
Excellent (5): The caption perfectly describes the image content with high accuracy, comprehensive detail, and excellent relevance to what is shown.

Notice:
Evaluate based on accuracy, relevance to the image, comprehensiveness, and level of detail. Do not allow caption length to influence your evaluation. Be as objective as possible.

Here is the input:
[The Image]
(See the attached image)
[The Generated Caption]
{caption}

Provide your analysis of how well the caption matches the image, then provide your final score in exactly this format on its own line: "Score: X" where X is a single number from 1 to 5."""


def load_model(model_path, device="cuda:0"):
    """Load Phi-4-reasoning-vision-15B."""
    from transformers import AutoModelForCausalLM, AutoProcessor

    print(f"[load_model] Loading Phi-4-reasoning-vision from {model_path}...")
    processor = AutoProcessor.from_pretrained(
        model_path, trust_remote_code=True
    )
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True,
        attn_implementation="sdpa",
    )
    model.eval()
    print(f"[load_model] Loaded successfully")
    return model, processor


def run_inference(model, processor, image_path, prompt, max_new_tokens=1024):
    """Run Phi-4 inference with image."""
    image = Image.open(image_path).convert("RGB")

    # Phi-4 uses <|image|> tag inline in text content
    messages = [
        {"role": "user", "content": f"<|image|>\n{prompt}"},
    ]

    # Process inputs — append <think> to force reasoning mode
    text_input = processor.tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    # No <think> for Polaris — reasoning mode gives no accuracy benefit
    # on captioning and is 154x slower (61.5s vs 0.4s per sample)
    # text_input = text_input + "<think>\n"

    inputs = processor(
        text=text_input,
        images=image,
        return_tensors="pt",
    ).to(model.device)

    input_length = inputs["input_ids"].shape[-1]

    with torch.no_grad():
        generation = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=False,
        )

    sequences = generation.sequences
    scores = generation.scores
    actual_input_length = sequences.shape[1] - len(scores)

    generated_ids = sequences[0, actual_input_length:].tolist()
    generated_text = processor.tokenizer.decode(generated_ids, skip_special_tokens=True)

    return generated_text, scores, sequences, actual_input_length


def extract_s2(scores, sequences, input_length, tokenizer):
    """Extract S2 logprobs and parsed score."""
    n_steps = len(scores)
    tokens = []
    for step_idx in range(n_steps):
        token_id = sequences[0, input_length + step_idx].item()
        token_str = tokenizer.decode([token_id]).strip()
        tokens.append(token_str)

    score_idx = _find_score_token(tokens)
    if score_idx is None:
        return [FALLBACK_LP] * 5, -1

    step_scores = scores[score_idx]
    log_probs = F.log_softmax(step_scores.float(), dim=-1)

    s2 = []
    for s in SCORE_TOKENS:
        token_ids = tokenizer.encode(s, add_special_tokens=False)
        if len(token_ids) >= 1:
            lp = log_probs[0, token_ids[0]].item()
            if not (lp == lp):
                lp = FALLBACK_LP
            s2.append(lp)
        else:
            s2.append(FALLBACK_LP)

    parsed_score = int(tokens[score_idx]) if tokens[score_idx] in SCORE_TOKENS else -1
    return s2, parsed_score


def _find_score_token(tokens):
    """Find score digit token index."""
    stripped = [t.strip().lower() for t in tokens]

    for i in range(len(tokens) - 1, -1, -1):
        if stripped[i] in SCORE_TOKENS:
            for j in range(max(0, i - 3), i):
                if "score" in stripped[j]:
                    return i

    for i in range(len(tokens) - 1, -1, -1):
        if "score" in stripped[i]:
            for j in range(i + 1, min(len(tokens), i + 5)):
                if stripped[j] in SCORE_TOKENS:
                    return j

    for i in range(len(tokens) - 1, -1, -1):
        if stripped[i] in SCORE_TOKENS:
            return i

    return None


def load_dataset():
    """Load Polaris captioning dataset."""
    import pandas as pd
    import numpy as np
    df = pd.read_csv('data/polaris/polaris_test_processed.csv')
    samples = []
    for i, row in df.iterrows():
        gt_discrete = int(round(row['score_mean'] * 4) + 1)
        gt_discrete = max(1, min(5, gt_discrete))
        samples.append({
            'idx': i,
            'image_path': f"data/polaris/images/{row['imgid']}",
            'caption': row['mt'],
            'gt_score': gt_discrete,
            'gt_score_continuous': row['score_mean'],
        })
    return samples


def main():
    parser = argparse.ArgumentParser(description="Phi-4 judge inference → CSV")
    parser.add_argument("--model-path", type=str,
                        default="models/Phi-4-reasoning-vision-15B")
    parser.add_argument("--output", type=str, required=True)
    parser.add_argument("--start-idx", type=int, default=0)
    parser.add_argument("--end-idx", type=int, default=None)
    parser.add_argument("--max-new-tokens", type=int, default=512)
    args = parser.parse_args()

    # Load dataset
    samples = load_dataset()
    print(f"[main] Dataset: {len(samples)} valid samples")

    end_idx = args.end_idx or len(samples)
    subset = samples[args.start_idx:end_idx]
    print(f"[main] Processing {len(subset)} samples (idx {args.start_idx} to {end_idx})")

    # Load model
    model, processor = load_model(args.model_path)

    # Prepare output
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    csv_file = open(args.output, "w", newline="")
    writer = csv.writer(csv_file)
    writer.writerow(["sample_id", "s2_lp1", "s2_lp2", "s2_lp3", "s2_lp4", "s2_lp5",
                      "gt_score", "parsed_score", "gt_score_continuous"])

    errors = 0
    pbar = tqdm(subset, desc="Phi-4 judge inference")

    for sample in pbar:
        try:
            prompt = PROMPT_TEMPLATE.format(
                caption=sample['caption'],
            )

            generated_text, scores, sequences, input_length = run_inference(
                model, processor, sample['image_path'], prompt,
                max_new_tokens=args.max_new_tokens,
            )

            s2, parsed_score = extract_s2(scores, sequences, input_length,
                                          processor.tokenizer)

            writer.writerow([sample['idx'], s2[0], s2[1], s2[2], s2[3], s2[4],
                             sample['gt_score'], parsed_score, sample['gt_score_continuous']])
            csv_file.flush()

            del scores, sequences
            torch.cuda.empty_cache()

        except Exception as e:
            print(f"\n[ERROR] Sample {sample['idx']}: {e}")
            errors += 1
            writer.writerow([sample['idx'], FALLBACK_LP, FALLBACK_LP, FALLBACK_LP,
                             FALLBACK_LP, FALLBACK_LP, sample['gt_score'], -1, sample['gt_score_continuous']])
            csv_file.flush()

        pbar.set_postfix(err=errors)

    csv_file.close()
    print(f"\n[main] Done! {len(subset) - errors} succeeded, {errors} errors")
    print(f"[main] Output: {args.output}")

    del model, processor
    gc.collect()
    torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
